import IndexHome from '@/components/indexHome'
import Head from 'next/head'
export default function Home() {
  
  return (
      <>
      <Head>
        <link rel="preload" href="//Tissues_050000.png" as="image"></link>
        <link rel="preload" href="//Tissues_050001.png" as="image"></link>
        <link rel="preload" href="//Tissues_050002.png" as="image"></link>
        <link rel="preload" href="//Tissues_050003.png" as="image"></link>
        <link rel="preload" href="//Tissues_050004.png" as="image"></link>
        <link rel="preload" href="//Tissues_050005.png" as="image"></link>
        <link rel="preload" href="//Tissues_050006.png" as="image"></link>
        <link rel="preload" href="//Tissues_050007.png" as="image"></link>
        <link rel="preload" href="//Tissues_050008.png" as="image"></link>
        <link rel="preload" href="//Tissues_050009.png" as="image"></link>
        <link rel="preload" href="//Tissues_050010.png" as="image"></link>
        <link rel="preload" href="//Tissues_050011.png" as="image"></link>
        <link rel="preload" href="//Tissues_050012.png" as="image"></link>
        <link rel="preload" href="//Tissues_050013.png" as="image"></link>
        <link rel="preload" href="//Tissues_050014.png" as="image"></link>
        <link rel="preload" href="//Tissues_050015.png" as="image"></link>
        <link rel="preload" href="//Tissues_050016.png" as="image"></link>
        <link rel="preload" href="//Tissues_050017.png" as="image"></link>
        <link rel="preload" href="//Tissues_050018.png" as="image"></link>
        <link rel="preload" href="//Tissues_050019.png" as="image"></link>
        <link rel="preload" href="//Tissues_050020.png" as="image"></link>
        <link rel="preload" href="//Tissues_050021.png" as="image"></link>
        <link rel="preload" href="//Tissues_050022.png" as="image"></link>
        <link rel="preload" href="//Tissues_050023.png" as="image"></link>
        <link rel="preload" href="//Tissues_050024.png" as="image"></link>
        <link rel="preload" href="//Tissues_050025.png" as="image"></link>
        <link rel="preload" href="//Tissues_050026.png" as="image"></link>
        <link rel="preload" href="//Tissues_050027.png" as="image"></link>
        <link rel="preload" href="//Tissues_050028.png" as="image"></link>
        <link rel="preload" href="//Tissues_050029.png" as="image"></link>
        <link rel="preload" href="//Tissues_050030.png" as="image"></link>
        <link rel="preload" href="//Tissues_050031.png" as="image"></link>
        <link rel="preload" href="//Tissues_050032.png" as="image"></link>
        <link rel="preload" href="//Tissues_050033.png" as="image"></link>
        <link rel="preload" href="//Tissues_050034.png" as="image"></link>
        <link rel="preload" href="//Tissues_050035.png" as="image"></link>
        <link rel="preload" href="//Tissues_050036.png" as="image"></link>
        <link rel="preload" href="//Tissues_050037.png" as="image"></link>
        <link rel="preload" href="//Tissues_050038.png" as="image"></link>
        <link rel="preload" href="//Tissues_050039.png" as="image"></link>
        <link rel="preload" href="//Tissues_050040.png" as="image"></link>
        <link rel="preload" href="//Tissues_050041.png" as="image"></link>
        <link rel="preload" href="//Tissues_050042.png" as="image"></link>
        <link rel="preload" href="//Tissues_050043.png" as="image"></link>
        <link rel="preload" href="//Tissues_050044.png" as="image"></link>
        <link rel="preload" href="//Tissues_050045.png" as="image"></link>
        <link rel="preload" href="//Tissues_050046.png" as="image"></link>
        <link rel="preload" href="//Tissues_050047.png" as="image"></link>
        <link rel="preload" href="//Tissues_050048.png" as="image"></link>
        <link rel="preload" href="//Tissues_050049.png" as="image"></link>
        <link rel="preload" href="//Tissues_050050.png" as="image"></link>
        <link rel="preload" href="//Tissues_050051.png" as="image"></link>
        <link rel="preload" href="//Tissues_050052.png" as="image"></link>
        <link rel="preload" href="//Tissues_050053.png" as="image"></link>
        <link rel="preload" href="//Tissues_050054.png" as="image"></link>
        <link rel="preload" href="//Tissues_050055.png" as="image"></link>
        <link rel="preload" href="//Tissues_050056.png" as="image"></link>
        <link rel="preload" href="//Tissues_050057.png" as="image"></link>
        <link rel="preload" href="//Tissues_050058.png" as="image"></link>
        <link rel="preload" href="//Tissues_050059.png" as="image"></link>
        <link rel="preload" href="//Tissues_050060.png" as="image"></link>
        <link rel="preload" href="//Tissues_050061.png" as="image"></link>
        <link rel="preload" href="//Tissues_050062.png" as="image"></link>
        <link rel="preload" href="//Tissues_050063.png" as="image"></link>
        <link rel="preload" href="//Tissues_050064.png" as="image"></link>
        <link rel="preload" href="//Tissues_050065.png" as="image"></link>
        <link rel="preload" href="//Tissues_050066.png" as="image"></link>
        <link rel="preload" href="//Tissues_050067.png" as="image"></link>
        <link rel="preload" href="//Tissues_050068.png" as="image"></link>
        <link rel="preload" href="//Tissues_050069.png" as="image"></link>
        <link rel="preload" href="//Tissues_050070.png" as="image"></link>
        <link rel="preload" href="//Tissues_050071.png" as="image"></link>
        <link rel="preload" href="//Tissues_050072.png" as="image"></link>
        <link rel="preload" href="//Tissues_050073.png" as="image"></link>
        <link rel="preload" href="//Tissues_050074.png" as="image"></link>
        <link rel="preload" href="//Tissues_050075.png" as="image"></link>
        <link rel="preload" href="//Tissues_050076.png" as="image"></link>
        <link rel="preload" href="//Tissues_050077.png" as="image"></link>
        <link rel="preload" href="//Tissues_050078.png" as="image"></link>
        <link rel="preload" href="//Tissues_050079.png" as="image"></link>
        <link rel="preload" href="//Tissues_050080.png" as="image"></link>
        <link rel="preload" href="//Tissues_050081.png" as="image"></link>
        <link rel="preload" href="//Tissues_050082.png" as="image"></link>
        <link rel="preload" href="//Tissues_050083.png" as="image"></link>
        <link rel="preload" href="//Tissues_050084.png" as="image"></link>
        <link rel="preload" href="//Tissues_050085.png" as="image"></link>
        <link rel="preload" href="//Tissues_050086.png" as="image"></link>
        <link rel="preload" href="//Tissues_050087.png" as="image"></link>
        <link rel="preload" href="//Tissues_050088.png" as="image"></link>
        <link rel="preload" href="//Tissues_050089.png" as="image"></link>
        <link rel="preload" href="//Tissues_050090.png" as="image"></link>
        <link rel="preload" href="//Tissues_050091.png" as="image"></link>
        <link rel="preload" href="//Tissues_050092.png" as="image"></link>
        <link rel="preload" href="//Tissues_050093.png" as="image"></link>
        <link rel="preload" href="//Tissues_050094.png" as="image"></link>
        <link rel="preload" href="//Tissues_050095.png" as="image"></link>
        <link rel="preload" href="//Tissues_050096.png" as="image"></link>
        <link rel="preload" href="//Tissues_050097.png" as="image"></link>
      </Head>
      <IndexHome></IndexHome>
      </>
  )
}
